### ISSUE TITLE
Error calling AccessTokenRequest

### ISSUE THREAD

**Issue by kimura97** [tradovate/api#11]
I have problem getting Access Token at the following code.

var accessTokenResponse = Authentication.GetAccessToken(LiveUrl, MyUsername, password);

I think the program was working fine yesterday. 
ID and Password are correct.
I got an error, "Tradovate.Services.Client.ApiException: Error calling AccessTokenRequest"
What could be the problem? I appreciate any advise.

**Comment by ThanhNguyenAppliedsw** [comment]
I also have the issue, it is urgent. 
Could you please let me know why we have the issue??

**Comment by victorwins** [comment]
We are removing support of TLS 1.0. Source codes of the sample will be updated soon
