### ISSUE TITLE
Accessing historical contracts and their data

### ISSUE THREAD

**Issue by tikidave** [tradovate/api#12]
[According to your website](https://tradovate.zendesk.com/hc/en-us/articles/217374728-Do-you-offer-historical-data-), Tradovate has 3 years of historical data we can access. 

Is it possible to get a list of all available historical contracts using the API?  I tried the `/contracts/suggest` endpoint but they are all current and future contracts. 

Please let me know the various resources/endpoints that could help me here, as I am interested in doing some data mining.

Mahalo!

**Comment by victorwins** [comment]
Please try /contract/find with ESH7
This endpoint returns any available contract that expired after January, 1st 2017. As a test of availability you can use UI of trader-d.tradovate.com (you need to switch "Do not autoroll contracts" in Application settings to on before it)

**Comment by tikidave** [comment]
I haven't tried the UI endpoint yet, but accessing via the UI showed no data for past contracts.  I tried ESM7 and ESH7.  Thoughts?

![2017-10-12_0839](https://user-images.githubusercontent.com/32719923/31496327-f1d8b2f8-af28-11e7-9c6a-eef7f9694cfa.png)

**Comment by victorwins** [comment]
if you are still experiencing a missed daily chart for ESH7, please send your username and I'll check why you don't receive it.
