### ISSUE TITLE
Swagger GUI Does Not Honor Valid Auth Tokens

### ISSUE THREAD

**Issue by mkvalor** [tradovate/api#13]
Hello,

When I enter my valid credentials into the Swagger website UI to obtain an auth token, I receive an HTTP 200 along with the response body containing the token and the other expected values.  However, when I use this token to authorize any other endpoint calls in the UI, the response is always 401 "Unauthorized" and an empty response body.

Clue: I noticed that the 'curl' equivalent line being generated in the Swagger UI sets the Authorization header like this: --header "Authorization: [token]", instead of adding the word "Bearer" in between, like this: --header "Authorization: Bearer [token]". 

This may be significant, because in my own shell terminal, the curl command without "Bearer" in it fails with response code 401  (just as it does in the Swagger UI), whereas the version that includes "Bearer" succeeds with a 200.

**Comment by victorwins** [comment]
Thank you for the note.  We use Swagger 2.0, this version requires to specify Bearer manually. It seems the next generation of Swagger has a better support for bearer tokens. We have plans to migrate to it in late 2018.
