### ISSUE TITLE
Access.md /account/list Example Returns Empty JSON array

### ISSUE THREAD

**Issue by mkvalor** [tradovate/api#14]
I have valid credentials for the Tradovate API.  I am able to obtain an auth token.  However, when I try to follow the example on:
https://github.com/tradovate/api/blob/master/Access.md#use-the-access-token
to use the new token to call the /account/list endpoint, it returns an empty JSON array in the body, instead of account details, as shown in the linked example.  Note that I do receive an HTTP 200 response with empty square brackets as the body, not an error code with an empty response body. Here is an example of the output, with an empty response, from my shell terminal, using a newly-obtained auth token:

```bash
mkvalor@LinuxLap01:~$ curl -i -X GET --header 'Accept: application/json' --header 'Authorization: Bearer <token_text_omitted_here>' 'https://live-api-d.tradovate.com/v1/account/list'
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 12 Oct 2017 07:46:26 GMT
Content-Type: application/json
Content-Length: 2
Connection: keep-alive
access-control-allow-origin: *
access-control-allow-credentials: true

[]
```

**Comment by victorwins** [comment]
Please try https://demo-api-d.tradovate.com/v1/account/list
live-api-d points to a staging environment for 'live' accounts and, probably, you don't have accounts there yet.

**Comment by mkvalor** [comment]
Yes, that was my problem.  The words "simulation engine" describing the demo link at
https://github.com/tradovate/api/blob/master/Access.md#overview
made me think it was for Replay functionality, instead of free trial testing.
