### ISSUE TITLE
HTTP 500 from /auth/renewaccesstoken in demo-api Environment

### ISSUE THREAD

**Issue by mkvalor** [tradovate/api#16]
Hello,

I am able to obtain an access token and call other endpoints (such as /account/list) in the demo-api environment.  However, if I attempt to call /auth/renewaccesstoken, passing in the same valid bearer authorization token header, the result of the call is an HTTP 500, with a response body indicating a different id for the Internal Server Error, each time I hit the end point.

I noticed from the endpoint description that it expects a JSON object in the request body.  However, the Swagger spec defines an object with no properties included.  So I have been sending {} as the empty JSON object for the request data.  I also tried filling in the request data JSON object with the original access token name/value pair, but that didn't work either.

Is this endpoint supposed to work?  If so, what am I missing that will successfully fulfill the requirements of the request?

**Comment by victorwins** [comment]
This endpoint should be called on live-api-d.tradovate.com

**Comment by mkvalor** [comment]
To be clear -- are you saying that a token I originally obtained from the demo-api-d hostname should be renewed via the live-api-d hostname?

If so, are there any/many other cases where I would expect to be able to keep hitting demo-api-d, but should only hit live-api-d?

**Comment by victorwins** [comment]
Starting from now in devel and starting from October, 22 in production you will receive a response with status code = 501 (Not Implemented) and body text like "This endpoint should be called on live-d.tradovate.com"

Generally, all endpoints that relates to a user entity or authentication should be called on live-api only. 

Access to contract library is allowed on both live-api and demo-api. 

Trading-related calls  (or, in general, any call that relates to a trading account) should go to live-api and demo-api depending on the account.

**Comment by mkvalor** [comment]
Thanks, got it.
