### ISSUE TITLE
How can I get CurrentProfitOrLoss and TotalTransactionCost in a Position?

### ISSUE THREAD

**Issue by ThanhNguyenAppliedsw** [tradovate/api#17]
I am using the https://github.com/tradovate/api/blob/master/csharp/services-api/docs/PositionsApi.md#getownedpositions api.

How can I get CurrentProfitOrLoss and TotalTransactionCost in a Position?

**Comment by victorwins** [comment]
You need to subscribe to quotes and use them for manual calculations of open p/l. Here is a sample how to subscribe and consume to quotes - https://github.com/tradovate/api/blob/master/csharp/samples-md/src/Program.cs#L41

What value should be in TotalTransactionCost?
