### ISSUE TITLE
How do we check the times with session with API?

### ISSUE THREAD

**Issue by ThanhNguyenAppliedsw** [tradovate/api#20]
I got this email from Tradovate:
"I just wanted to touch base with you on your API testing with Tradovate.
We've noticed that you've connected to the devel environment 6000+ times in the last 2 days with sessions lasting ~1 second each."

How can I check the times that is called?

How do I re-use the same session for each AT call instead of creating new session for each call?

**Comment by victorwins** [comment]
Please try to open the websocket once and share it between calls. If you don't need real-time updates, you can call endpoints via REST API and server side will take care about reusing your session.
