### ISSUE TITLE
Accessing historical minute data in archived contracts?

### ISSUE THREAD

**Issue by tikidave** [tradovate/api#21]
I am attempting to call `md/getChart` on an archived contract and it is returning no results.  Is it possible to access this historical contract data?  

Request:
```
md/getChart
2

{
  "symbol": "ESU7",
  "chartDescription": {
    "underlyingType": "MinuteBar",
    "elementSize": 240,
    "elementSizeUnit": "UnderlyingUnits"
  },
  "timeRange": {
    "asFarAsTimestamp": "2017-06-08T21:29:00.000Z"
  }
}
```
Response:
```
{ id: 54101, eoh: true }
```

**Comment by victorwins** [comment]
Minute bars are limited by two recent calendar weeks. There are no any plans to extend this period.
