### ISSUE TITLE
Not working on Windows Forms Application

### ISSUE THREAD

**Issue by pryashrma** [tradovate/api#22]
I am trying to duplicate the functionality of "ConsumingQuotes" [Program(Ln 32)] in C# Windows Form Application. The code works fine in "Console Application", but for Windows Form Application it gets struck in task.Wait()  forever. I am suspecting the issue is with the "Rest Client".

Please suggest how can I implement this code for Windows Form Application

**Comment by maxinovi** [comment]
Hi @pryashrma! 

We use blocking calls of Task.Wait() just for demonstration purposes, so could you please refactor your code for using async/await approach? Windows Forms has a specific thread model (UI thread), asynchronous tasks and blocking calls might affect it. We need to make sure that your code properly works with UI thread. 

Anyway, could you please provide your code or at least how it looks like? Then we could help in more details manner.
