### ISSUE TITLE
Websocket connect

### ISSUE THREAD

**Issue by Omate23** [tradovate/api#23]
Hi,
I am trying to write a small javascript websocket client to consume Tradvate API.

What I have right now is:
var WebSocketClient = require('websocket').client;
var client = new WebSocketClient();
client.connect('wss://demo-api-d.tradovate.com');

This fails with the message:
Error: Server responded with a non-101 status: 200 OK

Please help me how to connect, what I am missing.
Thank you,
Mate Ordody

**Comment by victorwins** [comment]
The server closes the connection if it is not authorized in timely manner. Please check https://github.com/tradovate/api/blob/master/WebSockets.md#authorization

**Comment by Omate23** [comment]
My problem is setting up a connection, I cannot send authorize or any requests, until my connection established. So what are the first steps? Do I need some form of authetication for the connection?

**Comment by victorwins** [comment]
can you show the full text of your example, including processing of Websocket events?

**Comment by Omate23** [comment]
Source:

var WebSocketClient = require('websocket').client;
var client = new WebSocketClient()

client.on('connectFailed', function(error) {
    console.log('Connect Error: ' + error.toString());
});

client.on('connect', function(connection) {
    console.log('WebSocket Client Connected');
    connection.on('error', function(error) {
        console.log("Connection Error: " + error.toString());
    });
    connection.on('close', function() {
        console.log('echo-protocol Connection Closed');
    });
    connection.on('message', function(message) {
        if (message.type === 'utf8') {
            console.log("Received: '" + message.utf8Data + "'");
        }
    });
});

client.connect('wss://demo-api-d.tradovate.com');


Output (Connection failed):
Connect Error: Error: Server responded with a non-101 status: 200 OK
Response Headers Follow:
server: nginx
date: Mon, 15 Jan 2018 08:45:02 GMT
content-length: 2
connection: keep-alive
access-control-allow-origin: *
access-control-allow-credentials: true


I did not try to send (conenction.send()) any requests, as I don't have connection object.

**Comment by victorwins** [comment]
Please try to connect to wss://demo-api-d.tradovate.com/websocket

**Comment by Omate23** [comment]
I have tried it, now it says:
Connect Error: Error: Server responded with a non-101 status: 404 Not Found

Here are the params and headers sent with the connection request (these were set by the websocket-client package), if it helps:
{ agent: false,
  hostname: 'demo-api-d.tradovate.com',
  port: '443',
  method: 'GET',
  path: '/websocket',
  headers:
   { Upgrade: 'websocket',
     Connection: 'Upgrade',
     'Sec-WebSocket-Version': '13',
     'Sec-WebSocket-Key': '3YAKldh/6581JgbrtK8ATA==',
     Host: 'demo-api-d.tradovate.com' } }

**Comment by victorwins** [comment]
I'm sorry, my fault: the correct url is wss://demo-api-d.tradovate.com/v1/websocket

**Comment by Omate23** [comment]
Yes, now I can connect, thank you!
But it's still not perfect.
I'm trying to send a POST accesstokenrequest. I felt this should be the first request. Unfortunately the answer is an empty string, as it is on any requests.

Code:
authobj = { name: 'XXxxxxxx', password: encodeURIComponent('zzzzzzz') }
msg('auth/accesstokenrequest', 1, '', JSON.stringify(authobj));

function msg(url, id, query, body)  {
    if (connection.connected) {
        console.log([url, id, query, body].join("\n"));
        connection.sendUTF([url, id, query, body].join("\n"));
    }
}


Output:
WebSocket Client Connected
Received: 'o'
auth/accesstokenrequest
1

{"name":"XXxxxxxx","password":"zzzzzzz"}
Received: ''
Received: 'h'
Received: 'h'
Received: 'h'
echo-protocol Connection Closed

**Comment by victorwins** [comment]
Unfortunately, our Websocket session doesn't support auth/accesstokenrequest endpoint and the call should go through regular REST API to get an access token (https://live-api-d.tradovate.com/v1/auth/accesstokenrequest in your case). When you have it, the first message in Websocket connection should be this one: https://github.com/tradovate/api/blob/master/WebSockets.md#authorization

**Comment by Omate23** [comment]
Yes, it works.
Thank you!

**Comment by Omate23** [comment]
Hi again,
I have one more question.
All my queries (I started with basic ones) goes through, and I receive answers to them in a[] frames in my onmessage handlers, as documented. I am happy with that.
But I am missing events, none I receive. I suppose I should get events from fills, position changes, etc.
Do I need to subscribe to messages somehow?

**Comment by victorwins** [comment]
To start getting events, please send the next user/syncrequest without parameters (https://swagger.tradovate.com/#!/Users/syncRequest): the response will contain a snapshot of your account activities and then you will receive updates for it.

**Comment by Omate23** [comment]
Yes, thank you.
