### ISSUE TITLE
How to get PnL (NetGain) of a Position?

### ISSUE THREAD

**Issue by freamdev** [tradovate/api#24]
I get all the position logs from the PositionsApi, and I need to get the Realized PnL and Open Pnl for every position, is this possible with the API?

Thank you for your help.

**Comment by victorwins** [comment]
You need to subscribe to real-time quotes to calculate Open P/L using quotes with net pos and net price. 

Realized P/L can be calculated as a sum of P/L of fill's pairs. You can get the collection of fill pairs for your position via this call: https://swagger.tradovate.com/#!/Positions/getOwnedFillPairs

**Comment by freamdev** [comment]
Thank you for your response.
