### ISSUE TITLE
Too Many Requests | HTTP 429 practices?

### ISSUE THREAD

**Issue by freamdev** [tradovate/api#25]
Sometimes our requests return the HTTP error code 429 ('Too Many Requests'), but we are not aware of its cause (as our usage is absolutely within reasonable limits). How can we avoid getting such an error? What are the relevant frequency/request number limits? And if we already received it, how long do we have to wait to be able to send requests again?

**Comment by victorwins** [comment]
Hard rate limit is 5000 requests per hour. The limit is evaluated for the previous hour. You need to wait until a number of past requests for current time minus one hour becomes less than 5000.

**Comment by victorwins** [comment]
Here are more details about limits: https://github.com/tradovate/api/blob/master/Access.md#request-rate-limits-and-time-penalty

**Comment by freamdev** [comment]
Thank you for the clarifications
