### ISSUE TITLE
The account is blocked when sending many requests to Tradovate in a day

### ISSUE THREAD

**Issue by ThanhNguyenAppliedsw** [tradovate/api#29]
Hi, 
I send 1055 requests to trade to Tradovate system in a day(get account, get position, get order, submit order, etc..). After that I got en error message from API, I also cannot trade on Tradovate Web UI. The message on Tradovate Web UI is "Too many requests" and my account is blocked. I can continue to trade on next day.
Note that: I used one access token for 1055 requests.

Does Tradovate system limit the request of an account in a day?
Do we have any solution to send more than 1055 requests in a day?

**Comment by victorwins** [comment]
Hello. Please contact Customer Service with details of the incident. Our limits are significantly higher and enforced for a shorter period of time than that.
