### ISSUE TITLE
No useable value for symbol

### ISSUE THREAD

**Issue by LoganWade** [tradovate/api#32]
I'm attempting to subscribe to a quote and I can't seem to get the request correct.  Can you give any guidance?  Thanks!

I'm connecting via websocket and authentication is successful but when I send this message to attempt subscribeQuote:
```
md/subscribeQuote
3
{"symbol":"ESM8"}
```

I get this response:

`a[{"s":400,"i":3,"d":"No usable value for symbol\nDid not find value which can be converted into java.lang.String"}]`

**Comment by LoganWade** [comment]
I found my mistake.  You can close this issue.

The documentation isn't perfectly clear on where to enter the symbol.  

Client docs state request format is this:

> an endpoint name as defined in Swagger specification
> a unique integer id of the request. The id should be unique in the scope of the current connection. This id will be used as a reference by server in the response messages (see "Response message" above)
> an optional field with **PARAMETERS** that identical to query parameters of REST API
> an optional field that is identical to a body parameter of REST API

While the market data docs state this:

> Create request **PARAMETERS**.
> 
> Request **parameters** are an object in JSON format.
> 
> Each request requires symbol **parameter** that specifies the contract for which market data are requested. Contract can be specified either by contract symbol or by contract ID:
> 
> {
>   "symbol":"ESM7" // Contract is specified by contract symbol
>   ...
> }
> // or
> {
>   "symbol":123456 // Contract is specified by contract ID
>   ...
> }

However, moving the symbol to the **body** section fixed the problem.

**Example:**
```
md/subscribeQuote
3

{"symbol":"ESM8"}
```

**Comment by victorwins** [comment]
Thank you for the details, we will try to clarify it in the doc
