### ISSUE TITLE
Unable to connect to Websocket URL 

### ISSUE THREAD

**Issue by mikegerst87** [tradovate/api#33]
I am using the sample app for C# and I am able to connect to the websocket with the demo url :
https://demo-api-d.tradovate.com/v1 but it disconnects after 30 seconds or so, I have attempted to use the SocketUrl: wss://demo-api-d.tradovate.com/v1/websocket    but it isn't recognized +0] ERROR: System.Exception: HTTP/1.1 404 Not Found

**Comment by victorwins** [comment]
our development servers were restarted today around this period of time. if you are still experiencing the issue, please check if you can connect with our web app (https://trader-d.tradovate.com)

**Comment by mikegerst87** [comment]
I am able to login on the web app but I still cant connect the websocket to wss://demo-api-d.tradovate.com/v1/websocket, like I said I can connect to the https://demo-api-d.tradovate.com/v1  but it closes the websocket connection after a minute or so

WebSocketUrl = "wss://demo-api-d.tradovate.com/v1/websocket";

 static WebSocketClient InitializeWebSocket(bool liveEnvironment)
        {
            Configuration.Default = new Configuration(new ApiClient(WebSocketUrl));
            Configuration.Default.ApiKey.Add("Authorization", AccessToken);
            Configuration.Default.ApiKeyPrefix.Add("Authorization", "Bearer");
            WebSocketClient websocketClient = new WebSocketClient(WebSocketUrl);
            Configuration.Default.ApiClient.RestClient = websocketClient;
            return websocketClient;
        }


WebSocketClient socketClientBroker = InitializeWebSocket(false);
            socketClientBroker.DataUpdated += WebsocketClient_DataUpdated;
            socketClientBroker.Closed += WebsocketClient_Closed;


           
            socketClientBroker.Opened += (sender, e) =>

            {
              

                Task.Run(() =>
                {
                    
                    account = Accounting.GetAccount(MyUserId);
                    Console.WriteLine(account.Id);
                    Accounting.ShowAccountActivities(account);
                    Accounting.StartRealtimeUpdates();

                    Accounting.PrepopulateCache();
                    ContractLibrary.PrepopulateCache();
                    Thread.Sleep(15000);
                    PlaceEsOso();


                });
               
                
                
            };

**Comment by mikegerst87** [comment]
It seems that the messages weren't firing regularly but it now that they are the connection stays open, so you can close this issue
