### ISSUE TITLE
Bracket Order Access Denied 

### ISSUE THREAD

**Issue by mikegerst87** [tradovate/api#34]
When I attempt to place a bracket order I get an UnknownReason: Access Denied error message. Below is the code I am using and the output 

var bracket1 = new RestrainedOrderVersion(Action: RestrainedOrderVersion.ActionEnum.Sell,
                                                                         OrderType: RestrainedOrderVersion.OrderTypeEnum.Limit,
                                                                         TimeInForce : RestrainedOrderVersion.TimeInForceEnum.Day,
                                                                         Price: 2850.50);
            var bracket2 = new RestrainedOrderVersion(Action: RestrainedOrderVersion.ActionEnum.Sell,
                                                                         OrderType: RestrainedOrderVersion.OrderTypeEnum.Stop,
                                                                         TimeInForce: RestrainedOrderVersion.TimeInForceEnum.Day,
                                                                         StopPrice: 2840.50
                                                                         );
            PlaceOSO oso = new PlaceOSO(Action: PlaceOSO.ActionEnum.Buy,
                                        AccountId: MyUserId,
                                        Symbol: "ESU8",
                                        OrderQty: 1,
                                        OrderType: PlaceOSO.OrderTypeEnum.Limit,
                                        Price : 2949.75,
                                        Bracket1 : bracket1,
                                        Bracket2 : bracket2);

[+2333] SENT: order/placeoso\n22\n\n{"action":"Buy","orderType":"Limit","accountId":6321,"symbol":"ESU8","orderQty":1,"price":2949.75,"bracket1":{"action":"Sell","orderType":"Limit","timeInForce":"Day","price":2850.5},"bracket2":{"action":"Sell","orderType":"Stop","timeInForce":"Day","stopPrice":2840.5}}
[+36] RECVD: a[{"s":200,"i":22,"d":{"failureReason":"UnknownRea...
class PlaceOsoResult {
  FailureReason: UnknownReason
  FailureText: Access is denied
  OrderId:
  Oso1Id:
  Oso2Id:
}

**Comment by victorwins** [comment]
Please confirm that you are the owner or has trading access to the account with id 6321.

**Comment by mikegerst87** [comment]
I do have access and I am able to authorize the connection you can see the authorization key in this output 
AUTH FOR OSO: Bearer Q3mGpFmG7WfMFpZaGsU544hXqT1dvV11wdCRCaLXMnO0qRDD4PUXBZRnffFI6YOdSC74JcJv4_VGqfiOZzyXjZWT0aU70qb-UotfhfzFX0ykX-0K0VNY8A1g-USZ1u5F2El3--ZONRqLgnUSbPx1ZzhlNJeQ0oX3T4aSyOTBxGxuh_sTqYaEagv-tUjj-QBYeCWrFMSkMA
[+49] SENT: order/placeoso\n11\n\n{"action":"Buy","orderType":"Limit","timeInForce":"Day","accountSpec":"DEMO06321","accountId":6321,"clOrdId":"1","symbol":"ESU8","orderQty":1,"price":2949.75,"bracket1":{"action":"Sell","orderType":"Limit","timeInForce":"Day","price":2850.5},"bracket2":{"action":"Sell","orderType":"Stop","timeInForce":"Day","stopPrice":2840.5}}
[+41] RECVD: a[{"s":200,"i":11,"d":{"failureReason":"UnknownRea...
class PlaceOsoResult {
  FailureReason: UnknownReason
  FailureText: Access is denied
  OrderId:
  Oso1Id:
  Oso2Id:
}

**Comment by mikegerst87** [comment]
I am the named person on the account, if that is what you mean

**Comment by victorwins** [comment]
the account with name DEMO06321 has another id, not 6321

**Comment by mikegerst87** [comment]
Ok I imagine that 6321 is the company account for the company I work for. How can I get this account verified.

**Comment by victorwins** [comment]
You don't need any additional verification. Please check the list of accounts that you receive from the server. The account entity includes its name and id.
