### ISSUE TITLE
Unable to authorize to websocket with access token

### ISSUE THREAD

**Issue by sdhiddi** [tradovate/api#35]
Hi,
I am able to connect to websocket "wss://md-api-d.tradovate.com/v1/websocket" using Java client and sessions were created successfully, but I didn't understand how to authroize using the access token (I am able to get the access token though)... 
I am looking specifically how to authorize my token for websocket in Java.. any example/sample would be great.!

This is how I am sending the message to websocket for authorization:
clientEndPoint.sendMessage("authorize\n" + "2\n\n" + accessToken);

please correct me if I am calling it wrong.

Thanks!

**Comment by victorwins** [comment]
Do you receive any response for your 'authorize' requests?

**Comment by sdhiddi** [comment]
I am not getting any response. right now I am seeing : Bad Gateway error

**Comment by sdhiddi** [comment]
Hi Victor,
No response is received from the authorize request, can you help resolve my issue ?
Thanks,

**Comment by sdhiddi** [comment]
Sorry, was accidentally closed, please look into this at your earliest possible

**Comment by victorwins** [comment]
I see in the logs that you were able to send authorization requests. Please confirm.

**Comment by sdhiddi** [comment]
@victorwins Yes, Thank you for your support...
The following statement==> userSession.getAsyncRemote().sendText(message); is changed to ==>userSession.getBasicRemote().sendText(message);
