### ISSUE TITLE
Can a WS "a" frame carry different types of messages?

### ISSUE THREAD

**Issue by skhilko** [tradovate/api#36]
> a - Array of json-encoded messages. For example: a["message"].

Given the two example from your documentation:
```
a[{"s":200,"i":23,"d":{"id":65543,"name":"CLZ6","contractMaturityId":6727}}]
a[{"e":"props","d":{"entityType":"order","eventType":"Created","entity":{"id":210518,"accountId":25,"contractId":560901,"timestamp":"2016-11-04T00:02:36.626Z","action":"Sell","ordStatus":"PendingNew","admin":false}}}]
```

- Is it safe to assume that one `a` frame would only contain messages of one type? For example, `"e": "props"` would not be intermixed with `"e": "shutdown"` or `"e": "md"` in an `a` frame.
- Can an `a` frame contain multiple client response messages? E.g. `a[{"s":200,"i":23,"d":{...}},{"s":200,"i":24,"d":{...}}]`?

**Comment by victorwins** [comment]
One 'a' frame can contain multiple message types/responses
