### ISSUE TITLE
Market subscription "delayed"

### ISSUE THREAD

**Issue by skhilko** [tradovate/api#37]
I'm getting `{ s: 200, i: 2, d: { mode: 'Delayed', subscriptionId: xxx }` response when I connect to `md/subscribeDOM` on the test environment. No market data is coming through.

- What does that mean on your end?
- What is the best way to handle this response? Terminate the session? Retry the connection in a certain interval?
- Is that possible on production?

Please advise.

**Comment by victorwins** [comment]
This means that you have no an eligible market data subscription

**Comment by skhilko** [comment]
@victorwins thanks for the response. Could you explain what this mode means? I think the absence of market data just coincided with an outage on your end. I've received 504 responses today while trying to connect to the data feed.

**Comment by victorwins** [comment]
Delayed market data shows with 10 minutes delay for some markets that requires a paid subscription.
What environment do you use that gave you 504 response?

**Comment by skhilko** [comment]
wss://md-api-d.tradovate.com/v1/websocket Sorry, it was 502 Bad gateway.

It's appeared to come back for some time and now it's down again.

**Comment by yssoe** [comment]
Actually just jumping in here to say I encounter some problems too lately, some times it doesn't work and then 10 minutes later it works again.

**Comment by victorwins** [comment]
this is a test environment and it goes up and down from time as we push new changes there. sorry about that.

**Comment by skhilko** [comment]
Is there a more stable production staging environment we can use?

**Comment by victorwins** [comment]
Not at this time.
