### ISSUE TITLE
Unable to getChart from md

### ISSUE THREAD

**Issue by sdhiddi** [tradovate/api#38]
@victorwins Hi Victor, I am trying to get the chart data and here is the request from my client after successful authorization:

md/getChart
60

{"symbol":"ESZ8","chartDescription":{"underlyingType":"MinuteBar","elementSize":15,"elementSizeUnit":"UnderlyingUnits"},"timeRange":{"asMuchAsElements":"66"}}

But I always receiving the response as follows...
a[{"s":404,"i":60,"d":"Not found: md/getChart"}]

Questions:
1. Am I missing anything in the request ?
2. Before requesting for the chart data, do I need to do "md/subscribeQuote" api call ?
3. Sending request format is incorrect ?
4. What else do you think it's missing/incorrect.

Appreciate your help in this regard..

**Comment by sdhiddi** [comment]
@victorwins I think I figured out...After doing the user/syncrequest call before getChart api call..it's returning the chart data...
One more question:
How to get the real-time data for a symbol in Renko bars (continuosly/streaming)... not able to figure out from the docs.. can you please help ?

**Comment by victorwins** [comment]
Unfortunately, Renko bars are not available as-is from the server.

**Comment by sdhiddi** [comment]
@victorwins okay, can you please let me know if there is any way to get the renko bars from charts ?

**Comment by sdhiddi** [comment]
@victorwins According to your market data api doc one can provide elementSizeUnit as Renko, what does it mean and how it works ? Any example would be great. When I use it as below
ChartDescription chartDescription = new ChartDescription();
		chartDescription.setUnderlyingType(UnderlyingTypeEnum.MINUTEBAR);
		chartDescription.setElementSize(1);
		chartDescription.setElementSizeUnit(ElementSizeUnitEnum.RENKO);


It always gives me the following error:
"a[
  {
    "s": 400,
    "i": 56,
    "d": "{\"violations\":[{\"constraint\":\"elementSizeUnit\",\"value\":\"Renko\",\"description\":\"Element Size Unit should be equal to ElementSizeUnit.UnderlyingUnits\"}]}"
  }
]"
