### ISSUE TITLE
Getting quote of specified future

### ISSUE THREAD

**Issue by DmytroMat** [tradovate/api#39]
I am using C# API library, but never have found how to get current quote from contract id, name or something else.
How can I easily get quotes using API?
Is there any C# function to get price/quote?
I don't want to use raw-socket mode.
I would like to know if you are providing the function on C# library or not.
Seems a lot of developers would feel inconvenient to get quote, while at usage of C# API.
We want you to provide simple functions to get quotes like other functions.
Thank you

**Comment by victorwins** [comment]
Here is the example for market data: https://github.com/tradovate/api/tree/master/csharp/samples-md/src

**Comment by DmytroMat** [comment]
Because the socket processing make the trading bot messed up with loop

**Comment by DmytroMat** [comment]
You must provide advanced functions to get market data

**Comment by victorwins** [comment]
Our plan is to keep our reference API as simple as possible and provide only basic building blocks. It is up to you how to mix-and-match them for your particular case.
