### ISSUE TITLE
Questions about order type

### ISSUE THREAD

**Issue by ThanhNguyenAppliedsw** [tradovate/api#4]
In the https://github.com/tradovate/api/blob/master/csharp/services-api/docs/OrdersApi.md#placeorder
There are Limit, MIT, Market, QTS, Stop, StopLimit, TrailingStop and TrailingStopLimit order type
Questions are that:
1) If I want to submit an order with the "Stop Loss Order" type, what order type should I use? Stop or StopLimit?

2) Simulator, If I want to submit an order with the "Trailing Stop Loss Order" type, what order type should I use? TrailingStop orTrailingStopLimit?

**Comment by weis-brian** [comment]
1.  To Place a Stop Loss you would want to use the "Stop" order type
2.  To place a Trailing Stop Loss you would want to use the "TrailingStop" order type

You can find some more details on the order types here: https://tradovate.zendesk.com/hc/en-us/articles/217733657-What-do-the-different-order-types-mean-
