### ISSUE TITLE
Websocket session "Closed abnormally" for market data

### ISSUE THREAD

**Issue by sdhiddi** [tradovate/api#40]
hi,
I am using the the following endpoint for websocket connection "wss://md-api-d.tradovate.com/v1/websocket"

Is it only because of the dev environment ? how to keep alive the socket connection ? any message needs to be sent constantly ?

is it possible that it can happen in live environment ?

**Comment by victorwins** [comment]
You need to send heartbeats - https://github.com/tradovate/api/blob/master/WebSockets.md#client-heartbeats
