### ISSUE TITLE
How can I connect the API to live account?

### ISSUE THREAD

**Issue by superdevelop** [tradovate/api#42]
I have developed a bot using API on the demo account.
It works fine now.(demo url = "https://demo-api-d.tradovate.com/v1" in this case)
private string GetServerUrl()
        {
            string url;
            if (optLive.Checked)
                url = "https://live-api.tradovate.com";// "https://live-api-d.tradovate.com/v1";
            else
                url = "https://demo-api.tradovate.com";// "https://demo-api-d.tradovate.com/v1";
            return url;
        }

but if url = "https://demo-api.tradovate.com", a bot doesn't work on calling API.
error is calling API.
Also, it doesn't work on live account.
I need to work a bot on live account.
Please help me.

**Comment by superdevelop** [comment]
Hello, please help me with that issues.

**Comment by victorwins** [comment]
What message was inside the exception?

**Comment by superdevelop** [comment]
![image](https://user-images.githubusercontent.com/18147411/49446860-aa466600-f807-11e8-92e8-f4db717cd411.png)

**Comment by superdevelop** [comment]
ex = {"Error calling GetAllFills: "}

**Comment by victorwins** [comment]
I see error code 401 which is HTTP status code for Unauthorized Error. 
Could you please check that your user works as expected via Tradovate Trader? 
Do you have two factor authentication enabled?

**Comment by superdevelop** [comment]
I enabled all on live and demo.
But same issues.

**Comment by victorwins** [comment]
Please try with disabled 2FA

**Comment by superdevelop** [comment]
well, I have checked it on disabled 2FA too.
but same issues.

**Comment by victorwins** [comment]
Please send your usernames via our Customer Service, both for development environment and production one.

**Comment by victorwins** [comment]
I've received the usernames. Could you please let me know the exact timestamp when you tried to login with the bot, used URL, and expiration time of received access token?

**Comment by superdevelop** [comment]
well, How can I get them?

**Comment by superdevelop** [comment]
![image](https://user-images.githubusercontent.com/18147411/49454345-87bc4900-f817-11e8-8548-3352fa3c975b.png)
please check this screenshort

**Comment by superdevelop** [comment]
but i can login with that account on tradovate.com
just error on coding.

**Comment by victorwins** [comment]
Please check that you are trying to login to with correct credentials.

**Comment by superdevelop** [comment]
-live
url = "https://live-api.tradovate.com";     
-demo       
 url = "https://demo-api.tradovate.com";
i am checking with demo account now.
i can login with that account on tradovate.com now.
![image](https://user-images.githubusercontent.com/18147411/49454580-ff8a7380-f817-11e8-99d5-c6263a9d8885.png)

**Comment by victorwins** [comment]
Please try the same access token request with curl

**Comment by superdevelop** [comment]
well, where can i try the same access token request with curl?

**Comment by victorwins** [comment]
Just in case - your screenshot of Tradovate Trader is for development environment.

Here is Swagger specs for the request that can be used with curl running in a regular command line: https://swagger.tradovate.com/#!/Authentication/accessTokenRequest

**Comment by victorwins** [comment]
Please try https://trader.tradovate.com for the production environment.

**Comment by superdevelop** [comment]
![image](https://user-images.githubusercontent.com/18147411/49455638-0d40f880-f81a-11e8-84ee-58ded6008505.png)
please check this screenshot

**Comment by victorwins** [comment]
Your Swagger screenshot points to the development environment. Please make sure you do not pass placeholders like "string" in the request.

**Comment by superdevelop** [comment]
what is coapplicantcode, appid, apVersion?

**Comment by victorwins** [comment]
It should be the same values that you use in your application.

**Comment by superdevelop** [comment]
![image](https://user-images.githubusercontent.com/18147411/49459343-6c563b80-f821-11e8-9da1-3ffc459600d6.png)
please check this screenshot

**Comment by victorwins** [comment]
do you use "UTT" as coapplicantCode in your application in development environment?

**Comment by superdevelop** [comment]
what is coapplicantCode?

**Comment by victorwins** [comment]
This is a 2FA code for a co-applicant of jointly opened account. If your account doesn't need it, do not use it in curl command.

**Comment by superdevelop** [comment]
hello.
I can't connect to serve urls now
https://live-api.tradovate.com, https://demo-api.tradovate.com
customer service team told me that I can use these serve url for using API.
but it gives calling API error on these server urls.
Please help me this issues.
I can't understand this problem.

**Comment by victorwins** [comment]
Did you try to login to https://trader.tradovate.com? It uses the same API.
