### ISSUE TITLE
Is possible to get streaming chart data?

### ISSUE THREAD

**Issue by leftcoastgeek** [tradovate/api#43]
I'm using the md/getChart ws endpoint on md-api-d.tradovate.com. I'm confused about whether or not there is a subscription is created. 

the [docs](https://github.com/tradovate/api/blob/master/MarketData.md#get-chart) say  
`A response for md/getChart request contains two subscription ID, historicalId and realtimeId. Client needs to store realtimeId value to properly cancel real-time chart subscription via md/cancelChart request`

Does that statement mean I should be getting back streaming chart data after I make the md/getChart request? I don't see streaming data. I see a payload of chart data and nothing else after that.

here are my questions:
1) Can I get streaming chart data from the api? if so what am I missing?
2) Is the chart data built in real time?
3) If I can't get back streaming chart data, can I poll on the socket? for example  when I get back a tick I send a request in for updated chart data with the `"asFarAsTimestamp":"2017-04-13T11:33Z"` defined with the last time I saw a bar? is there a better way?

thanks!

**Comment by victorwins** [comment]
1. The devel environment had issues around the time of your post. Did you have a chance to try it this week?
2. We have real-time and delayed chart data. It depends on your market data subscription. 
3.  After subscription, the server sends the bar updates via Websocket, no need to poll.
