### ISSUE TITLE
Problem with placing orders

### ISSUE THREAD

**Issue by igorchornuy** [tradovate/api#45]
Hello. When I try to create a new order, I get an error: {"failureReason":"UnknownReason","failureText":"Access is denied"}
I got this error using C # api. After that, I tried to reproduce it using your UI client. Using the web-site, everything works correctly. 
I also tried to send this request using Swagger. I got the same error. 

I'm using demo account - {Id:6757 Name:DEMO90000} and demo environment:"https://demo-api-d.tradovate.com/v1";

Here is an example of my curl:
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer VMDB5nrjLLUcSit3CaHDytAJXgtXim8A6z50XNW2RoWWRCvUKmUy64rKpjN0jnO_EzoR1gwsJGDr4mABxYQLnlHMM6snxG7QtGwvI_lc1CuG1TliUYtiMhW2eZsNSai2M4_zfLI25bxdrE5HuyUE57PlzvEs7EjjMv3ZFXYsII0TGqzNRV5u1t5uk8xJ1zzIGkt3nfi6' -d '{ 
   "accountId": 6757, 
   "action": "Buy", 
   "symbol": "E6H9", 
   "orderQty": 1, 
   "orderType": "Limit", 
   "price": 0.007, 
   "timeInForce": "Day"   
 } 
 ' 'https://demo-api-d.tradovate.com/v1/order/placeorder'

Response Header:
HTTP/1.1 200 OK
content-type: application/json
content-length: 66
access-control-allow-origin: *
access-control-allow-credentials: true
Date: Wed, 09 Jan 2019 22:29:48 GMT
Via: 1.1 google
Alt-Svc: clear

Response Body:
{"failureReason":"UnknownReason","failureText":"Access is denied"}

**Comment by victorwins** [comment]
Hello. We do not have E6H9 symbol. Please check the contract mapping with our Customer Service or find out the proper symbol in Tradovate Trader.

**Comment by igorchornuy** [comment]
Hello. Yes, the problem is solved. Because of my inattention, I did not notice that the formatting is different from the one we use. Thanks for the help.
