### ISSUE TITLE
How do we know Position status?

### ISSUE THREAD

**Issue by ThanhNguyenAppliedsw** [tradovate/api#5]
In the https://github.com/tradovate/api/blob/master/csharp/services-api/docs/PositionsApi.md#getpositions, 

How do we know Position status that is open or closed?

**Comment by victorwins** [comment]
Position should be treated as a closed one if the most recent Position entity for a combination of account and contract has a zero in NetPos (https://github.com/tradovate/api/blob/master/csharp/services-api/docs/Position.md)
