### ISSUE TITLE
How to get orderId/s when using orderStrategy endpoint.

### ISSUE THREAD

**Issue by redian** [tradovate/api#51]
Hi Tradovate.

Wondering whats the best way to get the `orderId` when placing an order using the `https://swagger.tradovate.com/#!/Orders/startOrderStrategy` endpoint.

From what i see the response after starting a strategy order using  `/orderStrategy/startorderstrategy` endpoint only contains the `orderStrategy.id`.  

Whats the best way to get the entry `orderId` given the `orderStrategyId` ?

Thanks in advance.

**Comment by victorwins** [comment]
Hello. This endpoint https://swagger.tradovate.com/#!/Orders/getOwnedOrderStrategyLinks should solve what you need: it gives you a list of links between the strategy and orders.

**Comment by redian** [comment]
Thanks a lot @victorwins
