### ISSUE TITLE
Market Data API Access Issue

### ISSUE THREAD

**Issue by thomasharmon808** [tradovate/api#52]
Hi,

when trying to send this request: "md/subscribeQuote\n3\n\n{'symbol': 'ESH9'}" over websocket connection, I am getting this error:

<img width="710" alt="screen shot 2019-02-13 at 4 27 42 pm" src="https://user-images.githubusercontent.com/26351993/52745100-4c26c380-2fac-11e9-8069-ed475187b502.png">

Can someone please tell me what I'm doing wrong? I emailed the support earlier and they told me my account has the proper access. I can post my code (using python) if needed. 

Thanks

**Comment by victorwins** [comment]
Please use double quotes in JSON

**Comment by thomasharmon808** [comment]
Ah ok, so thank you very much for the clarification to my silly issue... I had used the swagger-generated python client, and the to_str() function for a SubscribeQuote uses single quotes 😅

I hard coded the string and it works now, I will close this issue, thanks again
