### ISSUE TITLE
Why does the GetCashBalances have many same account? 

### ISSUE THREAD

**Issue by ThanhNguyenAppliedsw** [tradovate/api#6]
In the https://github.com/tradovate/api/blob/master/csharp/services-api/docs/AccountingApi.md#getcashbalance:
 How to know CashBalance we should use when getting?

**Comment by victorwins** [comment]
As soon as you have account id, you can request the list of cash balances for it like in that sample code: https://github.com/tradovate/api/blob/master/csharp/samples/src/Accounting.cs#L26
