### ISSUE TITLE
How do we get account Id after login to https://trader-d.tradovate.com/welcome?

### ISSUE THREAD

**Issue by ThanhNguyenAppliedsw** [tradovate/api#7]
How do we get account Id after login to https://trader-d.tradovate.com/welcome?
I only see the User Id.

**Comment by victorwins** [comment]
You can request the list of accessible accounts - here is a sample how to do it: https://github.com/tradovate/api/blob/master/csharp/samples/src/Accounting.cs#L16

**Comment by ThanhNguyenAppliedsw** [comment]
Sorry, I want to get this in the UI. is this possible?

**Comment by victorwins** [comment]
You can apply API-related code to UI
