### ISSUE TITLE
How do we submit an order with a symbol of 2020?

### ISSUE THREAD

**Issue by ThanhNguyenAppliedsw** [tradovate/api#8]
Example:  the "6EV7" is the "EURO FX" symbol of the October 2017,
So if I want to submit the symbol of October 2020. How can I do it? What is format?

**Comment by victorwins** [comment]
6EV0

**Comment by ThanhNguyenAppliedsw** [comment]
So if I want to submit the symbol of October 2027. Does the Tradovate support this?
If Yes, What is the format?

**Comment by victorwins** [comment]
Tradovate doesn't have such symbols

**Comment by ThanhNguyenAppliedsw** [comment]
Tradovate have symbols from 2017 to 2022 now. Right?

**Comment by victorwins** [comment]
so far - yes. But please contact Trade Desk for details about back month trading restrictions.
